FROM astrocrpublic.azurecr.io/runtime:3.0-4

RUN pip install pyspark==3.5.6 && \
     pip install apache-airflow-providers-google==16.1.0 && \
     pip install apache-airflow-providers-microsoft-mssql==4.3.2